package com.cristian.calculafacil.ui.theme

import androidx.compose.ui.graphics.Color

// ----- Luz -----
val PrimaryLight = Color(0xFF00696D)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF9CF1F5)
val OnPrimaryContainerLight = Color(0xFF002021)
val SecondaryLight = Color(0xFF4A6364)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCCE8E9)
val OnSecondaryContainerLight = Color(0xFF051F21)
val TertiaryLight = Color(0xFF9A4B2D)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFDBCC)
val OnTertiaryContainerLight = Color(0xFF371000)
val BackgroundLight = Color(0xFFF7FDFC)
val OnBackgroundLight = Color(0xFF181C1D)
val SurfaceLight = Color(0xFFF7FDFC)
val OnSurfaceLight = Color(0xFF181C1D)
val SurfaceVariantLight = Color(0xFFDAE4E5)
val OnSurfaceVariantLight = Color(0xFF3F494A)
val OutlineLight = Color(0xFF6F797A)
val OutlineVariantLight = Color(0xFFBEC8C9)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

// ----- Escuro -----
val PrimaryDark = Color(0xFF80D5D9)
val OnPrimaryDark = Color(0xFF003738)
val PrimaryContainerDark = Color(0xFF004F51)
val OnPrimaryContainerDark = Color(0xFF9CF1F5)
val SecondaryDark = Color(0xFFB1CCCD)
val OnSecondaryDark = Color(0xFF1B3435)
val SecondaryContainerDark = Color(0xFF324B4C)
val OnSecondaryContainerDark = Color(0xFFCCE8E9)
val TertiaryDark = Color(0xFFFFB597)
val OnTertiaryDark = Color(0xFF55210C)
val TertiaryContainerDark = Color(0xFF77351B)
val OnTertiaryContainerDark = Color(0xFFFFDBCC)
val BackgroundDark = Color(0xFF0E1415)
val OnBackgroundDark = Color(0xFFDDE4E4)
val SurfaceDark = Color(0xFF0E1415)
val OnSurfaceDark = Color(0xFFDDE4E4)
val SurfaceVariantDark = Color(0xFF3F494A)
val OnSurfaceVariantDark = Color(0xFFBEC8C9)
val OutlineDark = Color(0xFF889293)
val OutlineVariantDark = Color(0xFF3F494A)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)